import { useState } from 'react';
import { Brand } from './Brand';

const Arrow = () => <span aria-hidden="true">↗</span>;
const courses = [
  { title: 'Your first web page', subtitle: 'Make the internet a little more yours.', kind: 'HTML ESSENTIALS', cover: '/brand/html-cover.svg', href: '#/learn/first-web-page', meta: '2 lessons', className: 'navy' },
  { title: 'Web development foundations', subtitle: 'Understand the page. Connect the dots.', kind: 'WEB FOUNDATIONS', cover: '/images/code-detail-generated-v1.webp', href: '#/learn/web-foundations-intro', meta: '3 lessons', className: 'photo' },
  { title: 'Small builds. Real practice.', subtitle: 'Turn a blank editor into your first win.', kind: 'THE PRACTICE LAB', cover: '/brand/practice-cover.svg', href: '#/practice', meta: '4 HTML challenges', className: 'coral' },
];

function FirstWin() {
  const [heading, setHeading] = useState('My next big idea');
  return <div className="first-win"><div className="workbench-bar"><span><i /><i /><i /></span><span>your-first-page.html</span><span>HTML</span></div><div className="first-win-grid"><div className="first-win-editor"><p className="eyebrow">01 / GIVE IT A NAME</p><label htmlFor="first-heading">What would you like to build?</label><div className="heading-input"><code>&lt;h1&gt;</code><input id="first-heading" value={heading} onChange={event => setHeading(event.target.value)} maxLength={56} autoComplete="off" /><code>&lt;/h1&gt;</code></div><p>Change the text. See your heading come to life.</p></div><div className="first-win-output"><span className="eyebrow">02 / SEE YOUR FIRST LINE</span><strong aria-live="polite">{heading || 'Your idea goes here'}</strong><p>A little structure. A world of possibility.</p><span className="output-label">LIVE TEXT PREVIEW</span></div></div><div className="first-win-bottom"><span>No setup. No experience required.</span><a href="#/practice/profile-card">Now build the whole introduction <Arrow /></a></div></div>;
}

export function HomePage() {
  return <>
    <section className="bc-hero wrap">
      <div className="bc-hero-copy"><p className="bc-kicker"><span />FOR THE NEXT GENERATION OF BUILDERS</p><h1>Big ideas.<br />Real skills.<br /><span>Built by you.</span></h1><p className="bc-hero-lead">The next chapter of your life<br className="desktop-break" /> could start with a line of code.</p><p className="bc-hero-description">Learn the foundations, try things for yourself, and build something that matters. Practical software learning, with a place to begin.</p><div className="bc-actions"><a href="#/courses" className="button button-dark">Find your starting point <Arrow /></a><a href="#/practice" className="text-link">Try the practice lab <Arrow /></a></div><div className="bc-start-note"><span className="check-disc" aria-hidden="true">✓</span><p>Start free. Learn at your pace.<br /><strong>No account or payment needed.</strong></p></div></div>
      <div className="bc-hero-visual"><div className="hero-photo-frame"><img src="/images/hero-learner-generated-v1.webp" alt="AI-generated scene of a woman focused on a laptop" width="1122" height="1402" fetchPriority="high" /><div className="photo-caption"><span>THE BUILDER MINDSET</span><strong>Curiosity looks<br />good on you.</strong></div></div><div className="hero-corner-stamp" aria-hidden="true"><svg viewBox="0 0 100 100"><path d="M50 6v88M6 50h88M19 19l62 62m0-62L19 81" fill="none" stroke="currentColor" strokeWidth="4"/></svg></div><a href="#/practice/profile-card" className="hero-build-card"><div className="build-card-icon" aria-hidden="true">&lt;/&gt;</div><div><span>YOUR FIRST BUILD</span><strong>A page that says, “this is me.”</strong><p>Make your introduction <Arrow /></p></div></a><span className="photo-disclaimer">AI-generated imagery · <a href="#/credits">About the visuals</a></span></div>
    </section>
    <div className="bc-foundations wrap"><p>A SMALL START.<br /><strong>A STRONG FOUNDATION.</strong></p><div><span className="language-mark">&lt;/&gt;</span><span>HTML</span></div><div><span className="language-mark">{ '{ }' }</span><span>CSS</span></div><div><span className="language-mark js-mark">JS</span><span>JavaScript</span></div><p className="foundation-note">Understand the building blocks.<br />Then make them your own.</p></div>
    <section className="bc-course-section wrap"><div className="bc-section-heading"><div><p className="bc-kicker">YOUR FIRST STEP STARTS HERE</p><h2>Small beginnings.<br /><span>Serious possibilities.</span></h2></div><div><p>Choose a free introduction or jump into a small build. You do not need to know everything to begin.</p><a href="#/courses" className="text-link">Explore all introductions <Arrow /></a></div></div><div className="bc-course-grid">{courses.map((course, index) => <a href={course.href} className="bc-course-card" key={course.title}><div className={`bc-course-image ${course.className}`}><img src={course.cover} alt="" width="800" height="480" loading="lazy" /><span className="bc-course-number">0{index + 1}</span><span className="course-free">FREE TO START</span></div><div className="bc-course-body"><p className="eyebrow">{course.kind}</p><h3>{course.title}</h3><p>{course.subtitle}</p><div><span>Beginner friendly · {course.meta}</span><span className="course-arrow"><Arrow /></span></div></div></a>)}</div><p className="bc-honest-note">Original introductory learning, not a full qualification. No invented outcomes. Just a useful place to start.</p></section>
    <section className="bc-experience"><div className="wrap bc-experience-grid"><div className="experience-photo"><img src="/images/learning-together-generated-v1.webp" alt="AI-generated scene of three adults learning together at a laptop" width="1122" height="1402" loading="lazy" /><div className="experience-photo-label"><span className="mono">FROM “HOW?” TO “I MADE THIS.”</span><span aria-hidden="true">↗</span></div></div><div className="experience-copy"><p className="bc-kicker">LEARNING THAT GOES SOMEWHERE</p><h2>Less watching.<br /><span>More making.</span></h2><p>You do not learn to build by collecting open tabs. Read a little, try it yourself, and understand what changed.</p><ol><li><span>01</span><div><h3>Get the idea.</h3><p>Clear, original text lessons. No video buffering between you and the next step.</p></div></li><li><span>02</span><div><h3>Make it work.</h3><p>Write HTML, get specific feedback, and see an inert preview of what you made.</p></div></li><li><span>03</span><div><h3>Keep your momentum.</h3><p>Your reading record and practice drafts stay on your device. Pick up where you left off.</p></div></li></ol><a href="#/workspace" className="button button-lime">Open your learning desk <Arrow /></a></div></div></section>
    <section className="bc-try-section wrap"><div className="bc-section-heading"><div><p className="bc-kicker">DON'T JUST TAKE OUR WORD FOR IT</p><h2>Your first line.<br /><span>Right here, right now.</span></h2></div><p>Every project begins with something small. Give yours a heading, then step into the practice lab to build the rest.</p></div><FirstWin /></section>
    <section className="bc-support wrap"><div className="support-copy"><p className="bc-kicker">YOU CAN BUILD. YOU CAN ALSO ASK FOR HELP.</p><h2>A little guidance.<br />A clearer next step.</h2><p>Want structured training, a second pair of eyes on your code, or help turning a business problem into software? Tell us where you are starting.</p><div className="bc-actions"><a href="#/training" className="button button-dark">Talk about training <Arrow /></a><a href="#/services" className="text-link">Bring a project idea <Arrow /></a></div><p className="small-note">Training is by enquiry. Dates, availability and any fees are agreed separately.</p></div><div className="founder-real"><img src="/images/founder.webp" alt="Josiah Adeyemo, founder of Billion Codes" width="720" height="900" loading="lazy" /><div><span className="eyebrow">MEET THE PERSON BEHIND THE IDEA</span><strong>Josiah Adeyemo</strong><span>Software engineer. Founder. Fellow builder.</span><a href="#/about">More about Billion Codes <Arrow /></a></div></div></section>
    <section className="bc-finale"><div className="wrap"><Brand light /><p className="bc-kicker">YOUR NEXT CHAPTER IS NOT GOING TO WRITE ITSELF.</p><h2>Let's build<br /><span>something real.</span></h2><a href="#/courses" className="button button-lime">Start learning for free <Arrow /></a><p>No account. No payment. Just your curiosity.</p></div><span className="finale-outline" aria-hidden="true">B</span></section>
  </>;
}
