import { useState } from 'react';
import { PortalNav } from './Account';

const resources = [
  { title: 'Database Design, 2nd Edition', author: 'Adrienne Watt and Nelson Eng / BCcampus', kind: 'Textbook / PDF available', subject: 'Databases', summary: 'Explore relational databases, data models and the reasoning behind a well-structured database.', url: 'https://opentextbc.ca/dbdesign01/', licence: 'CC BY 4.0, except where otherwise noted', licenceUrl: 'https://opentextbc.ca/dbdesign01/front-matter/preface/' },
  { title: 'Think Python, 3rd Edition', author: 'Allen B. Downey / Green Tea Press', kind: 'Interactive textbook', subject: 'Python', summary: 'Start with programming concepts, then work through increasingly detailed Python examples and exercises.', url: 'https://greenteapress.com/wp/think-python-3rd-edition/', licence: 'CC BY-NC-SA 4.0 / official-site link only', licenceUrl: 'https://greenteapress.com/wp/think-python-3rd-edition/' },
  { title: 'CS50x', author: 'David J. Malan and the CS50 team / Harvard University', kind: 'Video lectures / exercises', subject: 'Computer science', summary: 'Follow the official introductory computer science course, with lectures and problem sets hosted by its creators.', url: 'https://cs50.harvard.edu/x/', licence: 'CC BY-NC-SA 4.0 / official-site link only', licenceUrl: 'https://cs50.harvard.edu/x/license/' },
  { title: 'Introduction to Computer Science', author: 'Jean-Claude Franchitti / OpenStax, Rice University', kind: 'Textbook / PDF available', subject: 'Computer science', summary: 'Use an academic introduction as a reference alongside your own programming practice.', url: 'https://openstax.org/details/books/introduction-computer-science/', licence: 'CC BY-NC-SA 4.0 / official-site link only', licenceUrl: 'https://openstax.org/books/introduction-computer-science/pages/preface' },
];
export function OpenResources() {
  const [search, setSearch] = useState('');
  const matches = resources.filter(item => `${item.title} ${item.subject} ${item.kind}`.toLowerCase().includes(search.toLowerCase()));
  return <div className="wrap page-section"><PortalNav /><div className="portal-heading"><div><p className="eyebrow">THE OPEN SHELF / CURATED, NOT COPIED</p><h1>Good knowledge<br />deserves a wider reach.</h1><p>A small, checked reading and viewing list from independent educators. These are external resources, not courses created or sold by Billion Codes.</p></div></div><div className="platform-notice">Open the original publisher for the textbook, PDF download or video lessons. No account here is required. External sites have their own privacy, accessibility and account policies; their completion records do not sync here.</div><div className="portal-search"><label htmlFor="resource-search">Find a resource</label><input id="resource-search" type="search" value={search} onChange={e => setSearch(e.target.value)} /></div><div className="portal-grid">{matches.map(item => <article className="portal-card" key={item.title}><span className="portal-tag">{item.kind}</span><h2>{item.title}</h2><p>{item.summary}</p><div className="resource-attribution"><p>By {item.author}</p><p><a href={item.licenceUrl} target="_blank" rel="noreferrer">{item.licence} (opens in a new tab)</a></p></div><a className="text-link" href={item.url} target="_blank" rel="noreferrer">Learn at the original source <span className="sr-only">(opens in a new tab)</span></a></article>)}</div>{!matches.length && <p role="status">No resources match your search.</p>}<section className="portal-section platform-panel"><h2>Attribution stays with the work.</h2><p>We link to the official editions and retain each creator's credit. A publicly available course is not automatically licensed for redistribution or resale. None of these links imply an endorsement, partnership or accreditation.</p><p>Resource links and licence notices last checked 11 September 2026.</p><a href="https://open.umn.edu/opentextbooks/" target="_blank" rel="noreferrer">Explore the Open Textbook Library (opens in a new tab)</a></section></div>;
}
