import { useDeferredValue, useState } from 'react';
import { challenges, gradeChallenge, MAX_CODE_LENGTH, previewHTML, recordAttempt, saveDraft, type Feedback } from '@billioncodes/learning';
import { changeProgress, useWorkspace } from './learningStore';

export function PracticeLab({ id }: { id?: string }) {
  const { progress, notice } = useWorkspace();
  const challenge = challenges.find(item => item.id === id);
  const [feedback, setFeedback] = useState<Feedback | null>(null);
  const [resetting, setResetting] = useState(false);
  const code = challenge ? progress.drafts[challenge.id] ?? challenge.starter : '';
  const deferredCode = useDeferredValue(code);
  if (!id) return <div className="wrap page-section"><div className="page-heading"><p className="bc-kicker">THE PRACTICE LAB / HTML FOUNDATIONS</p><h1>Less theory.<br />More “I made this.”</h1><p>Four small, real HTML exercises. Write code, check its structure, and learn from specific feedback. No JavaScript is executed. Your drafts stay on this device.</p></div><div className="exercise-grid">{challenges.map((item, index) => <a href={`#/practice/${item.id}`} className="exercise-card" key={item.id}><span className="eyebrow">BUILD 0{index + 1} / ABOUT {item.minutes} MIN</span><span className="exercise-glyph" aria-hidden="true">{['<h1>', '<ul>', '<form>', '<main>'][index]}</span><h2>{item.title}</h2><p>{item.brief}</p><div><span>{progress.solved[item.id] ? 'Completed once on this device' : 'Start building'}</span><span aria-hidden="true">↗</span></div></a>)}</div><a className="text-link" href="#/workspace">Your learning desk <span aria-hidden="true">↗</span></a></div>;
  if (!challenge) return <div className="wrap page-section"><h1>That exercise is not here.</h1><a href="#/practice">Choose an available exercise</a></div>;
  function edit(value: string) { changeProgress(current => saveDraft(current, challenge!.id, value)); setFeedback(null); }
  function check() { setFeedback(gradeChallenge(challenge!.id, code)); changeProgress(current => recordAttempt(current, challenge!.id, code)); }
  return <div className="wrap page-section lab-page"><a className="back-link" href="#/practice">← All exercises</a><div className="lab-heading"><div><p className="bc-kicker">YOUR NEXT SMALL WIN</p><h1>{challenge.title}</h1><p>{challenge.brief}</p></div><a href="#/workspace" className="text-link">Learning desk ↗</a></div>{notice && <p role="status" className="storage-notice">{notice}</p>}<div className="lab-grid"><section className="lab-editor"><div className="workbench-bar"><span>index.html</span><span>HTML ONLY</span></div><label htmlFor="exercise-code">Your HTML</label><textarea id="exercise-code" spellCheck={false} autoCapitalize="off" autoCorrect="off" value={code} maxLength={MAX_CODE_LENGTH} onChange={event => edit(event.target.value)} aria-describedby="code-note" /><p id="code-note">{code.length.toLocaleString()} / {MAX_CODE_LENGTH.toLocaleString()} characters. Do not put passwords or private information in practice code.</p><div className="lab-actions"><button className="button button-lime" onClick={check}>Check my build <span aria-hidden="true">↗</span></button><button className="reset-link" onClick={() => setResetting(true)}>Reset code</button></div>{resetting && <div className="inline-confirm"><p>Replace this draft with the starter code? Your earlier completion record will remain.</p><button onClick={() => { edit(challenge.starter); setResetting(false); }}>Replace draft</button><button onClick={() => setResetting(false)}>Keep editing</button></div>}</section><section className="lab-results"><div className="lab-preview-heading"><h2>Your preview</h2><span className="badge badge-paper">INERT HTML</span></div><iframe title="Safe HTML practice preview" srcDoc={previewHTML(deferredCode)} sandbox="" tabIndex={-1} /><p className="small-note">A structural preview, not a full browser: scripts, styles, navigation and submission are disabled. Unknown elements are omitted.</p><details className="lab-hint"><summary>Need a nudge?</summary><p>{challenge.hint}</p></details><div className="build-feedback" aria-live="polite" aria-atomic="true">{feedback ? <><h2>{feedback.passed ? 'You made it work.' : 'A few things to work on.'}</h2>{feedback.error && <p>{feedback.error}</p>}<ul>{feedback.checks.map(item => <li key={item.label} className={item.passed ? 'check-pass' : 'check-miss'}><span aria-hidden="true">{item.passed ? '✓' : '○'}</span><span>{item.passed ? 'Passed: ' : 'Try again: '}{item.label}</span></li>)}</ul><p className="small-note">These checks test the exercise goals, not every HTML or accessibility rule. Local practice is not certification.</p></> : <><h2>Your brief</h2><ul>{challenge.goals.map(goal => <li key={goal}>{goal}</li>)}</ul><p className="small-note">Choose “Check my build” when you are ready.</p></>}</div></section></div></div>;
}
