import { useState } from 'react';
import { request } from './api';
import { AccountGate, PortalNav, jsonBody, message, useAccount } from './Account';
import { RemoteNotice, useRemote } from './LearningPortal';

type Cohort = { id: string; title: string; year: number; quarter: number; status: string; acceptingApplications: boolean; opensAt: string | null; closesAt: string | null; startsAt: string | null; details: string; tuitionNote: string; format: string };
type Details = { track: string; format: string; experience: string; goals: string; phone: string };
type Application = { id: string; cohortId: string; cohortTitle: string; status: string; version: number; data: Details; updatedAt: string };
const date = (value: string | null) => value ? new Date(value).toLocaleDateString('en-NG', { dateStyle: 'medium', timeZone: 'Africa/Lagos' }) : 'To be announced';
export function TrainingLanding() {
  const state = useRemote<{ cohorts: Cohort[] }>('/api/v2/cohorts');
  return <div className="wrap page-section"><div className="portal-heading"><div><p className="eyebrow">A SHARED DIRECTION</p><h1>Learn with intention.<br />Build with others.</h1><p>Two intended training windows each year. Create an account first, then prepare an application for an announced intake. Dates, format, fees and places are confirmed separately for each cohort.</p></div><a className="button button-dark" href="#/training-dashboard">Open training dashboard</a></div><div className="portal-grid">{[['Q1', 'Early-year intake', 'January to March'], ['Q4', 'Late-year intake', 'October to December']].map(([quarter, title, months]) => <section className="portal-card" key={quarter}><span className="portal-window">{quarter}</span><h2>{title}</h2><p>{months}. This is a planning window, not an announced start date.</p></section>)}</div><section className="portal-section"><h2>Announced intakes</h2><RemoteNotice state={state} />{state.value && !state.value.cohorts.length && <div className="platform-notice">No intake dates or fees have been announced yet. You can create your account now; applications open only for published cohorts.</div>}<CohortCards cohorts={state.value?.cohorts || []} /></section><div className="platform-panel"><h2>Know your next step.</h2><p>Create your account, save an application draft, submit during the application window, then follow the review in your dashboard. An application or offer is not a confirmed enrolment or payment.</p><a className="text-link" href="#/training-dashboard">Prepare for an intake</a></div></div>;
}
function CohortCards({ cohorts }: { cohorts: Cohort[] }) {
  return <div className="portal-grid">{cohorts.map(cohort => <article className="portal-card" key={cohort.id}><span className="portal-tag">{cohort.year} / Q{cohort.quarter} / {cohort.acceptingApplications ? 'Applications open' : cohort.status}</span><h3>{cohort.title}</h3><p>{cohort.details}</p><p>Start: {date(cohort.startsAt)}<br />Applications close: {date(cohort.closesAt)}<br />Format: {cohort.format}</p><p>{cohort.tuitionNote}</p><a className="text-link" href={`#/apply/${cohort.id}`}>{cohort.acceptingApplications ? 'Apply for this intake' : 'Prepare a draft'}</a></article>)}</div>;
}
function Dashboard() {
  const state = useRemote<{ applications: Application[] }>('/api/v2/training/applications');
  const intakes = useRemote<{ cohorts: Cohort[] }>('/api/v2/cohorts');
  return <><div className="portal-heading"><div><p className="eyebrow">YOUR TRAINING JOURNEY</p><h1>A clear view<br />of what comes next.</h1><p>Your saved drafts and submitted applications are private to your account. An offer is not a confirmed place until arrangements are agreed with the team.</p></div></div><RemoteNotice state={state} /><div className="portal-grid">{state.value?.applications.map(application => <article className="portal-card" key={application.id}><span className="portal-tag">{application.status.replaceAll('-', ' ')}</span><h2>{application.cohortTitle}</h2><p>{application.data.track || 'Track not chosen yet'}</p><p>Last saved: {date(application.updatedAt)}</p><a className="text-link" href={`#/apply/${application.cohortId}`}>View application</a></article>)}</div>{state.value?.applications.length === 0 && <p className="platform-notice">You have not started an application yet. Choose an announced intake below when one is available.</p>}<section className="portal-section"><h2>Intakes</h2><RemoteNotice state={intakes} /><CohortCards cohorts={intakes.value?.cohorts || []} />{intakes.value?.cohorts.length === 0 && <p>Intakes are planned for Q1 and Q4. Exact dates and fees have not been announced.</p>}</section></>;
}
export function TrainingDashboard() { const { user } = useAccount(); return <div className="wrap page-section"><PortalNav /><AccountGate><Dashboard key={user?.id} /></AccountGate></div>; }
function ApplicationEditor({ cohort, saved, reload }: { cohort: Cohort; saved?: Application; reload: () => void }) {
  const [data, setData] = useState<Details>(saved?.data || { track: '', format: 'undecided', experience: '', goals: '', phone: '' });
  const [consent, setConsent] = useState(false), [pending, setPending] = useState(false), [notice, setNotice] = useState('');
  const editable = !saved || ['draft', 'withdrawn'].includes(saved.status);
  const { user } = useAccount();
  async function save(submit: boolean) {
    setPending(true); setNotice('');
    try { await request(`/api/v2/training/cohorts/${cohort.id}/application`, jsonBody({ data, version: saved?.version || 0, submit, consent }, 'PUT')); reload(); }
    catch (error) { setNotice(message(error)); } finally { setPending(false); }
  }
  async function withdraw() {
    if (!window.confirm('Withdraw this application? It will no longer be under review.')) return;
    setPending(true); setNotice('');
    try { await request(`/api/v2/training/applications/${saved!.id}/withdraw`, jsonBody({ version: saved!.version })); reload(); }
    catch (error) { setNotice(message(error)); } finally { setPending(false); }
  }
  return <div className="training-layout"><aside className="platform-panel"><p className="eyebrow">{cohort.year} / Q{cohort.quarter}</p><h2>{cohort.title}</h2><p>{cohort.details}</p><p>Training starts: {date(cohort.startsAt)}<br />Application deadline: {date(cohort.closesAt)}</p><p>{cohort.tuitionNote}</p><p className="training-status">Status: {saved?.status || 'Not started'}</p>{saved && <p className="small-note">Reference: {saved.id}<br />Saved: {date(saved.updatedAt)}</p>}</aside><section className="platform-panel"><h2>{editable ? 'Your starting point.' : 'Your application.'}</h2><p>{user?.name} / {user?.email}</p><form className="platform-form" onSubmit={e => { e.preventDefault(); void save(true); }}><label>What would you like to learn?<input required maxLength={80} minLength={2} disabled={!editable} value={data.track} onChange={e => setData({ ...data, track: e.target.value })} /></label><label>Preferred format<select value={data.format} disabled={!editable} onChange={e => setData({ ...data, format: e.target.value })}><option value="undecided">Not sure yet</option><option value="online">Online</option><option value="physical">Physical</option></select></label><label>Your experience<textarea required maxLength={1000} minLength={2} disabled={!editable} value={data.experience} onChange={e => setData({ ...data, experience: e.target.value })} /></label><label>What do you want to achieve?<textarea required maxLength={2000} minLength={10} disabled={!editable} value={data.goals} onChange={e => setData({ ...data, goals: e.target.value })} /></label><label>Phone (optional)<input type="tel" autoComplete="tel" maxLength={30} disabled={!editable} value={data.phone} onChange={e => setData({ ...data, phone: e.target.value })} /></label>{editable && <><label className="platform-check"><input type="checkbox" checked={consent} onChange={e => setConsent(e.target.checked)} /><span>I agree that Billion Codes can store and review this application. This does not reserve a place or authorize a payment.</span></label><div className="platform-actions"><button className="button button-outline" type="button" disabled={pending} onClick={() => save(false)}>Save draft</button><button className="button button-dark" disabled={pending || !consent || !cohort.acceptingApplications}>Submit application</button></div>{!cohort.acceptingApplications && <p className="small-note">This intake is not accepting submissions. You can still save a draft.</p>}</>}{saved && !['withdrawn', 'declined'].includes(saved.status) && <button className="text-link" type="button" disabled={pending} onClick={withdraw}>Withdraw application</button>}{pending && <p role="status">Saving your application...</p>}{notice && <p role="alert" className="platform-error">{notice}</p>}</form></section></div>;
}
function ApplicationData({ id }: { id: string }) {
  const intakes = useRemote<{ cohorts: Cohort[] }>('/api/v2/cohorts');
  const state = useRemote<{ applications: Application[] }>('/api/v2/training/applications');
  const cohort = intakes.value?.cohorts.find(item => item.id === id), saved = state.value?.applications.find(item => item.cohortId === id);
  return <><RemoteNotice state={intakes} /><RemoteNotice state={state} />{cohort && state.value && <ApplicationEditor key={`${id}:${saved?.version || 0}`} cohort={cohort} saved={saved} reload={state.reload} />}{intakes.value && !cohort && <p role="alert">This intake was not found.</p>}</>;
}
export function ApplyPage({ id }: { id: string }) { return <div className="wrap page-section"><PortalNav /><AccountGate><ApplicationData id={id} /></AccountGate></div>; }
